/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BAlert {
    /**
    * The alert display state
    */
    'show': boolean;
    /**
    * The alert variant
    */
    'variant': string;
  }
  interface BAlertAttributes extends StencilHTMLAttributes {
    /**
    * The alert display state
    */
    'show'?: boolean;
    /**
    * The alert variant
    */
    'variant'?: string;
  }

  interface BBadge {
    /**
    * The alert variant
    */
    'variant': string;
  }
  interface BBadgeAttributes extends StencilHTMLAttributes {
    /**
    * The alert variant
    */
    'variant'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BAlert': Components.BAlert;
    'BBadge': Components.BBadge;
  }

  interface StencilIntrinsicElements {
    'b-alert': Components.BAlertAttributes;
    'b-badge': Components.BBadgeAttributes;
  }


  interface HTMLBAlertElement extends Components.BAlert, HTMLStencilElement {}
  var HTMLBAlertElement: {
    prototype: HTMLBAlertElement;
    new (): HTMLBAlertElement;
  };

  interface HTMLBBadgeElement extends Components.BBadge, HTMLStencilElement {}
  var HTMLBBadgeElement: {
    prototype: HTMLBBadgeElement;
    new (): HTMLBBadgeElement;
  };

  interface HTMLElementTagNameMap {
    'b-alert': HTMLBAlertElement
    'b-badge': HTMLBBadgeElement
  }

  interface ElementTagNameMap {
    'b-alert': HTMLBAlertElement;
    'b-badge': HTMLBBadgeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
