/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BAlert {
    /**
    * The alert display state
    */
    'show': boolean;
    /**
    * The alert variant
    */
    'variant': string;
  }
  interface BAlertAttributes extends StencilHTMLAttributes {
    /**
    * The alert display state
    */
    'show'?: boolean;
    /**
    * The alert variant
    */
    'variant'?: string;
  }

  interface BBadge {
    /**
    * The badge variant
    */
    'variant': string;
  }
  interface BBadgeAttributes extends StencilHTMLAttributes {
    /**
    * The badge variant
    */
    'variant'?: string;
  }

  interface BBreadcrumb {
    /**
    * The breadcrumb items
    */
    'items': {text: string, href: string, active: boolean}[] | string;
  }
  interface BBreadcrumbAttributes extends StencilHTMLAttributes {
    /**
    * The breadcrumb items
    */
    'items'?: {text: string, href: string, active: boolean}[] | string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BAlert': Components.BAlert;
    'BBadge': Components.BBadge;
    'BBreadcrumb': Components.BBreadcrumb;
  }

  interface StencilIntrinsicElements {
    'b-alert': Components.BAlertAttributes;
    'b-badge': Components.BBadgeAttributes;
    'b-breadcrumb': Components.BBreadcrumbAttributes;
  }


  interface HTMLBAlertElement extends Components.BAlert, HTMLStencilElement {}
  var HTMLBAlertElement: {
    prototype: HTMLBAlertElement;
    new (): HTMLBAlertElement;
  };

  interface HTMLBBadgeElement extends Components.BBadge, HTMLStencilElement {}
  var HTMLBBadgeElement: {
    prototype: HTMLBBadgeElement;
    new (): HTMLBBadgeElement;
  };

  interface HTMLBBreadcrumbElement extends Components.BBreadcrumb, HTMLStencilElement {}
  var HTMLBBreadcrumbElement: {
    prototype: HTMLBBreadcrumbElement;
    new (): HTMLBBreadcrumbElement;
  };

  interface HTMLElementTagNameMap {
    'b-alert': HTMLBAlertElement
    'b-badge': HTMLBBadgeElement
    'b-breadcrumb': HTMLBBreadcrumbElement
  }

  interface ElementTagNameMap {
    'b-alert': HTMLBAlertElement;
    'b-badge': HTMLBBadgeElement;
    'b-breadcrumb': HTMLBBreadcrumbElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
